"""remove wordpress and wechat publish fields from video model

Revision ID: 45203e75019e
Revises: 6946f1772137
Create Date: 2025-08-14 09:43:13.315159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45203e75019e'
down_revision = '6946f1772137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('wechat_published_at')
        batch_op.drop_column('published_to_wechat')
        batch_op.drop_column('wordpress_published_at')
        batch_op.drop_column('published_to_wordpress')
        batch_op.drop_column('wordpress_post_url')
        batch_op.drop_column('wordpress_post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wordpress_post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wordpress_post_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('published_to_wordpress', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wordpress_published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('published_to_wechat', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wechat_published_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###
