"""empty message

Revision ID: 57a314a67c73
Revises: 6946f1772137
Create Date: 2025-08-11 10:47:50.888946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a314a67c73'
down_revision = '6946f1772137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform_name', 'config_key', 'environment', name='_user_platform_key_env_uc')
    )
    op.create_table('tag_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('mapping_name', sa.String(length=100), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform_name', 'tag_name', 'environment', name='_user_platform_tag_env_uc')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wordpress_post_id', sa.Integer(), nullable=True),
    sa.Column('wordpress_post_url', sa.String(length=500), nullable=True),
    sa.Column('published_to_wordpress', sa.Boolean(), nullable=True),
    sa.Column('wordpress_published_at', sa.DateTime(), nullable=True),
    sa.Column('published_to_wechat', sa.Boolean(), nullable=True),
    sa.Column('wechat_published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wechat_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('app_id', sa.String(length=100), nullable=False),
    sa.Column('app_secret', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', 'is_active', name='_user_account_id_active_uc')
    )
    with op.batch_alter_table('wechat_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_wechat_accounts_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_wechat_accounts_user_id', ['user_id'], unique=False)

    op.create_table('wordpress_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('site_url', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'site_url', 'is_active', name='_user_site_url_active_uc')
    )
    with op.batch_alter_table('wordpress_sites', schema=None) as batch_op:
        batch_op.create_index('ix_wordpress_sites_site_url', ['site_url'], unique=False)
        batch_op.create_index('ix_wordpress_sites_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordpress_sites', schema=None) as batch_op:
        batch_op.drop_index('ix_wordpress_sites_user_id')
        batch_op.drop_index('ix_wordpress_sites_site_url')

    op.drop_table('wordpress_sites')
    with op.batch_alter_table('wechat_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_wechat_accounts_user_id')
        batch_op.drop_index('ix_wechat_accounts_account_id')

    op.drop_table('wechat_accounts')
    op.drop_table('videos')
    op.drop_table('tag_mappings')
    op.drop_table('platform_configs')
    op.drop_table('articles')
    op.drop_table('users')
    # ### end Alembic commands ###
