"""Add WordPress and WeChat publish fields to Video model

Revision ID: 6946f1772137
Revises: 11b9c7652802
Create Date: 2025-08-09 18:07:43.494619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6946f1772137'
down_revision = '11b9c7652802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wordpress_post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wordpress_post_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('published_to_wordpress', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wordpress_published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('published_to_wechat', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wechat_published_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('wechat_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('_user_account_id_uc'), type_='unique')
        batch_op.create_unique_constraint('_user_account_id_active_uc', ['user_id', 'account_id', 'is_active'])
        batch_op.create_index('ix_wechat_accounts_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_wechat_accounts_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('wordpress_sites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('_user_site_url_uc'), type_='unique')
        batch_op.create_unique_constraint('_user_site_url_active_uc', ['user_id', 'site_url', 'is_active'])
        batch_op.create_index('ix_wordpress_sites_site_url', ['site_url'], unique=False)
        batch_op.create_index('ix_wordpress_sites_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordpress_sites', schema=None) as batch_op:
        batch_op.drop_index('ix_wordpress_sites_user_id')
        batch_op.drop_index('ix_wordpress_sites_site_url')
        batch_op.drop_constraint('_user_site_url_active_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_user_site_url_uc'), ['user_id', 'site_url'])

    with op.batch_alter_table('wechat_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_wechat_accounts_user_id')
        batch_op.drop_index('ix_wechat_accounts_account_id')
        batch_op.drop_constraint('_user_account_id_active_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_user_account_id_uc'), ['user_id', 'account_id'])

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('wechat_published_at')
        batch_op.drop_column('published_to_wechat')
        batch_op.drop_column('wordpress_published_at')
        batch_op.drop_column('published_to_wordpress')
        batch_op.drop_column('wordpress_post_url')
        batch_op.drop_column('wordpress_post_id')

    # ### end Alembic commands ###
