"""add wp_tag and wp_footer fields to wordpress_sites

Revision ID: 8f8b8b8b8b8b
Revises: 45203e75019e
Create Date: 2025-08-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8b8b8b8b8b'
down_revision = '45203e75019e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordpress_sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wp_tag', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('wp_footer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordpress_sites', schema=None) as batch_op:
        batch_op.drop_column('wp_footer')
        batch_op.drop_column('wp_tag')

    # ### end Alembic commands ###