"""add wx_footer field to wechat_accounts

Revision ID: 9a9a9a9a9a9a
Revises: 8f8b8b8b8b8b
Create Date: 2025-08-15 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9a9a9a9a9a'
down_revision = '8f8b8b8b8b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wx_footer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_accounts', schema=None) as batch_op:
        batch_op.drop_column('wx_footer')

    # ### end Alembic commands ###