"""add activation fields to user

Revision ID: add_activation_fields
Revises: aef6c4a723eb
Create Date: 2026-03-25 16:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_activation_fields'
down_revision = 'aef6c4a723eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_token', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('activation_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activation_expires_at')
        batch_op.drop_column('activation_token')

    # ### end Alembic commands ###