"""add platform cookies table

Revision ID: e0dbbceb1d2e
Revises: 4214102143f0
Create Date: 2025-08-22 12:35:49.893863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0dbbceb1d2e'
down_revision = '4214102143f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_cookies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('cookies', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform_name', name='_user_platform_cookies_uc')
    )
    with op.batch_alter_table('platform_cookies', schema=None) as batch_op:
        batch_op.create_index('ix_platform_cookies_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_cookies', schema=None) as batch_op:
        batch_op.drop_index('ix_platform_cookies_user_id')

    op.drop_table('platform_cookies')
    # ### end Alembic commands ###
